version: '3'
services: 
  products-app:
    build: .
    volumes: 
      - ./:/var/www
    depends_on: 
      - products-app-mysql
      - products-app-redis
  
  products-app-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports: 
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment: 
      MYSQL_DATABASE: products-app
      MYSQL_ROOT_PASSWORD: root
  
  products-app-redis:
    image: redis:alpine
    expose: 
      - "6376"

  products-app-nginx:
    build: ./.docker/nginx
    restart: always
    ports: 
      - "8001:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - products-app

